DataFormatException: Added class. InflaterInputStream: Replaced instances of throwing IOException appropriately with DataFormatException. InflaterInputStreamTest: Changed selected test cases to expect DataFormatException.